# Generated by Django 5.1.3 on 2024-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="year_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
