# Generated by Django 5.1.3 on 2024-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
